### ISSUE TITLE
Adjust labels

### ISSUE THREAD

**Issue by dsheldon** [darkecology/roostui#18]
New labels should be:

1 / non-roost / transparent / negative
2 / swallow-roost / not transparent / positive
3 / weather-roost / transparent / positive
4 / unknown-noise-roost / transparent / positive
5 / AP-roost / transparent / positive
4 / other-roost / transparent / ignore
6 / duplicate / transparent / ignore
7 / bad-track / transparent / ignore (we might consider them as positive and use only first three frames)

**Comment by msubhransu** [comment]
What is the notation here?

**Comment by dsheldon** [comment]
number / label / UI behavior / training behavior

Is there an option in detectron2 to "ignore" an example? If not, I'd suggest we consider the ignore categories as positive examples. For the most part, detections in these categories are roosts of some type.

**Comment by dsheldon** [comment]
Fixed with 395c7d6b67c6ad560f7e9efdff3e2c848a8bee0b
